### PR TITLE
Baseline feature

### PR DESCRIPTION
**Pull request by torbacz**
## Description

- Add baseline feature.

## How Has This Been Tested?

- Ran samples.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [x] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [x] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Comment by torbacz** [comment]
Not sure why "PR Checks / nanoFramework / NuGets using latest version (pull_request)" failed. According to my VisualStudio all packages are up to date.

**Comment by torbacz** [comment]
Also, please delete branch "feature/baseline" from nanoframework repo (I don't have permission)

**Review by josesimoes — APPROVED** [review]
LGTM! Nice improvement. 👍🏻

**Comment by josesimoes** [comment]
@torbacz all checks are now 🟢 , there was a glitch in the github action. And baseline branch has been deleted, as requested.

**Pull request merged**
